export type Language = 'en' | 'sw' | 'sh';

export const translations = {
  en: {
    title: 'Agri-Expert SSA',
    subtitle: 'Your Digital Agricultural Advisor',
    health: 'Health',
    weather: 'Weather',
    market: 'Market',
    map: 'Map',
    saved: 'Saved',
    uploadImage: 'Upload or Take Photo',
    analyze: 'Analyze Crop',
    analyzing: 'Analyzing...',
    location: 'Enter Location (e.g., Nakuru, Kenya)',
    getSchedule: 'Get Planting Schedule',
    loading: 'Loading...',
    saveAdvice: 'Save for Offline',
    noSaved: 'No saved advice yet.',
    swahili: 'Kiswahili',
    english: 'English',
    sheng: 'Sheng',
    syncStatus: 'Optimized for Rural Connectivity',
    treatmentPlan: 'Treatment Plan',
    organicPriority: 'Prioritizing organic and local solutions.',
    chatTitle: 'Mshauri wa Kilimo',
    chatPlaceholder: 'Ask a follow-up question...',
    chatSend: 'Send',
    outbreakTitle: 'Regional Health Map',
    outbreakSubtitle: 'Live Pest & Disease Alerts',
    riskHigh: 'High Risk',
    riskMedium: 'Medium Risk',
    riskLow: 'Low Risk',
    diagnosisPrompt: 'You are an expert plant pathologist for Sub-Saharan Africa. Analyze this image of a crop. Identify the disease if any. Provide a detailed "Treatment Plan" that PRIORITIZES organic and local solutions suitable for smallholder farmers in Kenya. Also include chemical options as a last resort. Respond in English, Swahili, and Sheng.',
    schedulePrompt: (location: string) => `You are a climate-smart agriculture expert. Provide a detailed planting schedule for ${location}. Include best crops for the current season, soil preparation, and water management tips. Focus on localized advice for Kenya. Respond in English, Swahili, and Sheng.`,
    marketPrompt: (location: string) => `Provide current market price trends for major crops in ${location}, Kenya. Include advice on where to sell and how to get the best prices. Respond in English, Swahili, and Sheng.`,
    chatPrompt: (history: string) => `You are "Mshauri wa Kilimo", a friendly agricultural advisor. Answer the farmer's question based on the previous diagnosis and context. Use a mix of English, Swahili, and Sheng as appropriate for a Kenyan farmer. Keep advice practical and organic-first. History: ${history}`,
    error: 'An error occurred. Please try again.',
    selectImage: 'Please select an image first.',
    enterLocation: 'Please enter a location.',
  },
  sw: {
    title: 'Agri-Expert SSA',
    subtitle: 'Mshauri Wako wa Kilimo Dijitali',
    health: 'Afya',
    weather: 'Hali ya Hewa',
    market: 'Soko',
    map: 'Ramani',
    saved: 'Yaliyohifadhiwa',
    uploadImage: 'Pakia au Piga Picha',
    analyze: 'Chunguza Mazao',
    analyzing: 'Inachunguza...',
    location: 'Weka Mahali (mfano, Nakuru, Kenya)',
    getSchedule: 'Pata Ratiba ya Kupanda',
    loading: 'Inapakia...',
    saveAdvice: 'Hifadhi kwa Matumizi ya Baadaye',
    noSaved: 'Hakuna ushauri uliohifadhiwa bado.',
    swahili: 'Kiswahili',
    english: 'Kiingereza',
    sheng: 'Sheng',
    syncStatus: 'Imeboreshwa kwa Muunganisho wa Vijijini',
    treatmentPlan: 'Mpango wa Matibabu',
    organicPriority: 'Kutoa kipaumbele kwa suluhisho za kikaboni na za kienyeji.',
    chatTitle: 'Mshauri wa Kilimo',
    chatPlaceholder: 'Uliza swali la ziada...',
    chatSend: 'Tuma',
    outbreakTitle: 'Ramani ya Afya ya Kikanda',
    outbreakSubtitle: 'Tahadhari za Wadudu na Magonjwa',
    riskHigh: 'Hatari Kubwa',
    riskMedium: 'Hatari ya Kati',
    riskLow: 'Hatari Ndogo',
    diagnosisPrompt: 'Wewe ni mtaalamu wa magonjwa ya mimea katika Afrika Kusini mwa Jangwa la Sahara. Chunguza picha hii ya zao. Tambua ugonjwa ikiwa upo. Toa "Mpango wa Matibabu" wa kina unaotoa KIPAUMBELE kwa suluhisho za kikaboni na za kienyeji zinazofaa kwa wakulima wadogo nchini Kenya. Pia jumuisha chaguzi za kemikali kama hatua ya mwisho. Jibu kwa Kiingereza, Kiswahili, na Sheng.',
    schedulePrompt: (location: string) => `Wewe ni mtaalamu wa kilimo kinachozingatia hali ya hewa. Toa ratiba ya kina ya kupanda kwa ${location}. Jumuisha mazao bora kwa msimu wa sasa, maandalizi ya udongo, na vidokezo vya usimamizi wa maji. Lenga ushauri wa ndani wa Kenya. Jibu kwa Kiingereza, Kiswahili, na Sheng.`,
    marketPrompt: (location: string) => `Toa mienendo ya sasa ya bei ya soko kwa mazao makuu katika ${location}, Kenya. Jumuisha ushauri wa mahali pa kuuza na jinsi ya kupata bei bora. Jibu kwa Kiingereza, Kiswahili, na Sheng.`,
    chatPrompt: (history: string) => `Wewe ni "Mshauri wa Kilimo", mshauri rafiki wa kilimo. Jibu swali la mkulima kulingana na utambuzi uliopita na muktadha. Tumia mchanganyiko wa Kiingereza, Kiswahili, na Sheng inavyofaa kwa mkulima wa Kenya. Weka ushauri wa vitendo na wa kikaboni kwanza. Historia: ${history}`,
    error: 'Hitilafu imetokea. Tafadhali jaribu tena.',
    selectImage: 'Tafadhali chagua picha kwanza.',
    enterLocation: 'Tafadhali weka mahali.',
  },
  sh: {
    title: 'Agri-Expert SSA',
    subtitle: 'Mshauri Wako wa Shamba Dijitali',
    health: 'Health',
    weather: 'Weather',
    market: 'Soko',
    map: 'Map',
    saved: 'Saved',
    uploadImage: 'Piga picha au upload',
    analyze: 'Checki Mazao',
    analyzing: 'Inacheki...',
    location: 'Weka mtaa (e.g., Nakuru, Kenya)',
    getSchedule: 'Pata Ratiba ya Kupanda',
    loading: 'Inaload...',
    saveAdvice: 'Hifadhi kwa baadaye',
    noSaved: 'Bado haujasave kitu.',
    swahili: 'Kiswahili',
    english: 'English',
    sheng: 'Sheng',
    syncStatus: 'Imeboreshwa kwa network ya ocha',
    treatmentPlan: 'Mpango wa Tiba',
    organicPriority: 'Tunaprioritize organic na local solutions.',
    chatTitle: 'Mshauri wa Kilimo',
    chatPlaceholder: 'Uliza swali hapa...',
    chatSend: 'Tuma',
    outbreakTitle: 'Health Map ya Mtaa',
    outbreakSubtitle: 'Alerts za Wadudu na Magonjwa',
    riskHigh: 'Danger Sana',
    riskMedium: 'Danger Kidogo',
    riskLow: 'Iko Sawa',
    diagnosisPrompt: 'Wewe ni expert wa plant diseases SSA. Checki hii picha ya crop. Tambua ugonjwa. Toa "Mpango wa Tiba" poa inayoprioritize organic na local solutions za msee wa shamba mdogo Kenya. Pia weka chemical options kama last resort. Jibu kwa English, Swahili, na Sheng.',
    schedulePrompt: (location: string) => `Wewe ni expert wa climate-smart agriculture. Toa ratiba poa ya kupanda kwa ${location}. Weka crops fiti za msimu huu, soil preparation, na water management tips. Lenga ushauri wa Kenya. Jibu kwa English, Swahili, na Sheng.`,
    marketPrompt: (location: string) => `Toa bei za soko za sasa za mazao makuu ${location}, Kenya. Weka ushauri wa mahali pa kuuza na jinsi ya kupata bei fiti. Jibu kwa English, Swahili, na Sheng.`,
    chatPrompt: (history: string) => `Wewe ni "Mshauri wa Kilimo", mshauri fiti wa kilimo. Jibu swali ya mkulima kulingana na diagnosis ya kitambo. Tumia English, Swahili, na Sheng fiti kwa msee wa Kenya. Weka ushauri wa kienyeji mbele. Historia: ${history}`,
    error: 'Kuna shida. Jaribu tena.',
    selectImage: 'Chagua picha kwanza.',
    enterLocation: 'Weka mtaa kwanza.',
  }
};
